### ISSUE TITLE
Bless absolute, relative or remote path in css @import  

### ISSUE THREAD

**Issue by san4osq** [BlessCSS/grunt-bless#35]
Please add option `pathType` to

```
options: {
      pathType: "absolute" ------> by default
}
```

in main.css
```
@import "D:/www/styles/style1.css"                   -> absolute path
@import "style1.css"                                 -> relative path
@import "http://example.com/css/styles.css"          -> remote path

h1, h2 ....{
    font-size: 32px;
}
some css code .....
```

Thank you!

**Comment by AaronAsAChimp** [comment]
A couple of thoughts. The current paths, "relative" in your example, should work in 99.9% of situations, because import paths are relative to the stylesheet not the document. It does occur to me that there is a bug with the way relative paths are created which can cause 404 errors.

Second, the absolute path in your example is a bad idea and it should definitely not be the default. 

Lastly, using string tokens like that is bad design and would require multiple options to be able to configure it properly. This is how I would configure such an option:

```js
options: {
    root: 'http://example.com/css/'
}
```
